name: aqua_care
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  fluentui_icons: ^1.0.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  google_maps_flutter: ^2.9.0
  location: ^7.0.1
  http: ^1.2.2
  google_generative_ai: ^0.4.6
  flutter_spinkit: ^5.2.1
  smooth_page_indicator: ^1.2.0+3
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/play_store_512.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/utils/water_sources.json

  # Fonts can be added here if needed
  # fonts:
  #   - family: YourFont
  #     fonts:
  #       - asset: fonts/YourFont.ttf
